sudo: false
language: python
install:
- echo # pip install -r scripts/requirements.txt
script:
- "./scripts/deploy.sh"
notifications:
  slack:
    rooms:
      secure: G0POm9Hor9kj/5j8p3GkStPE1CaIeZU3Dhbxe1GZVngjNB46t9NJ7U4y1/DSIvwRzspxwC42FldCWV4TMdr5kn+cfpZMEq/+N0Lz4NiS3nd79uchkKHk1VrlVSZzIp8Q3pEeCM9mHAH3+Z+7Q+gp3MzUo5UKFOlXOumhq5FKNBM=
